/*correct but inconsistent use of 3rd library parameter*/
proc r;
submit;
df<-sd2df("sashelp.cars")
df2sd(df,"cars_r","work")
endsubmit;
run;

/*all char columns in dataset generated by df2sd( ) are 32767 long*/
/*sashelp.cars is 192kb, the new cars dataset in work is 3MB*/
/*this is a big table!*/
proc contents data=work.cars_r;
run;
proc contents data=sashelp.cars;
run;


Proc r;
Submit;
# Helper: generate SAS LENGTH statement from a data frame
sas_length_stmt <- function(df,min_width = 1L) {
 char_cols <-names(df)[sapply(df,is.character)]
if (length(char_cols) == 0) return("")
parts <-sapply(char_cols, function(col) {
 max_len <- max(nchar(df[[col]],type = "bytes"),na.rm = TRUE)
 max_len <- max(max_len,min_width,na.rm = TRUE)
 paste0(col, " $",max_len)
 })
 paste("length",paste(parts,collapse = " "), ";")
 }
dfcars<-sd2df("sashelp.cars")

# Apply length fix before df2sd (parquet engine produces $32767 otherwise)
 symput("cars_lengths",sas_length_stmt(dfcars))
 df2sd(dfcars, "cars_raw", "work")
cat("dfCars table written to work.cars_raw\n")
 endsubmit;
run;

/* Re-stamp correct character lengths, then drop the raw dataset */
data work.cars_r;
 &cars_lengths.
 set work.cars_raw;
run;

proc contents data=work.cars_r;
run;